package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import hello.TodoItem;
import hello.TodoItemsRepository;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/todoitems") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called todoListRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TodoItemsRepository todoItemsRepository;
    private String currentDate;
    private SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    @GetMapping(path="/")
    public @ResponseBody Iterable<TodoItem> getAllTodoItems() {
        // This returns a JSON or XML with the users
        return todoItemsRepository.findAll();
    }

}